// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Support both legacy JWT keys and new API key format (sb_publishable_...)
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
let activeAccessToken: string | null = null;

export function setSupabaseAccessToken(token: string | null): void {
  activeAccessToken = token ?? null;

  if (activeAccessToken) {
    try {
      supabase.realtime.setAuth(activeAccessToken);
    } catch (_error) {
      // Ignore realtime auth errors in environments without realtime usage.
    }
  }
}

export function getSupabaseAccessToken(): string | null {
  return activeAccessToken;
}

// Import the Supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      fetch: async (input, init) => {
        const headers = new Headers(init?.headers ?? {});

        if (activeAccessToken && !headers.has("Authorization")) {
          headers.set("Authorization", `Bearer ${activeAccessToken}`);
        }

        return fetch(input, {
          ...init,
          headers,
        });
      },
    },
  }
);
